version: "3"
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-thrl6p}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-insecure}